# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSR', '0002_auto_20180213_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videometadata',
            name='category',
        ),
    ]
